export type MythFactAnswer = "Mitos" | "Fakta";
export type MythFactItem = {
  id: string;
  category: string;
  statement: string;
  answer: MythFactAnswer;
  explanation: string;
  takeaway: string;
};

export const mythFactItems: MythFactItem[] = [
  { id:"urologi-1", category:"Urologi", statement:"Menahan buang air kecil terlalu lama adalah kebiasaan yang aman jika tidak terasa sakit.", answer:"Mitos", explanation:"Menahan BAK berulang dapat menimbulkan rasa tidak nyaman dan pada sebagian orang dapat mengganggu kebiasaan berkemih yang sehat.", takeaway:"Biasakan BAK saat tubuh memberi sinyal dan jangan sengaja menahannya terlalu lama." },
  { id:"urologi-2", category:"Urologi", statement:"Urine yang sangat pekat bisa menjadi tanda tubuh kurang cairan.", answer:"Fakta", explanation:"Urine yang lebih gelap atau pekat dapat muncul ketika asupan cairan kurang, walau warna urine juga bisa dipengaruhi makanan, obat, dan kondisi lain.", takeaway:"Pantau hidrasi dan perhatikan perubahan warna urine yang menetap atau disertai keluhan lain." },
  { id:"urologi-3", category:"Urologi", statement:"Nyeri saat buang air kecil sebaiknya selalu diabaikan karena biasanya hilang sendiri.", answer:"Mitos", explanation:"Nyeri saat BAK dapat berkaitan dengan iritasi, infeksi, batu, atau penyebab lain. Keluhan yang menetap perlu dievaluasi.", takeaway:"Cari bantuan bila nyeri menetap, disertai demam, darah dalam urine, atau sulit BAK." },
  { id:"ginjal-1", category:"Ginjal", statement:"Minum air cukup membantu mendukung fungsi ginjal dan keseimbangan cairan tubuh.", answer:"Fakta", explanation:"Ginjal mengatur cairan dan membuang sisa metabolisme melalui urine. Asupan cairan yang cukup membantu proses tersebut pada orang sehat.", takeaway:"Minum secara teratur sesuai kebutuhan tubuh, aktivitas, cuaca, dan kondisi kesehatan." },
  { id:"ginjal-2", category:"Ginjal", statement:"Semua sakit pinggang pasti berasal dari ginjal.", answer:"Mitos", explanation:"Nyeri pinggang dapat berasal dari otot, tulang, saraf, ginjal, atau organ lain. Lokasi nyeri saja tidak cukup untuk menentukan penyebabnya.", takeaway:"Perhatikan gejala penyerta seperti demam, mual, nyeri BAK, atau perubahan urine." },
  { id:"menstruasi-1", category:"Menstruasi", statement:"Saat menstruasi, seseorang tidak boleh berolahraga sama sekali.", answer:"Mitos", explanation:"Aktivitas fisik ringan sampai sedang umumnya tetap boleh bila tubuh terasa nyaman dan tidak ada larangan medis.", takeaway:"Pilih aktivitas sesuai kondisi tubuh dan berhenti jika nyeri atau pusing memburuk." },
  { id:"menstruasi-2", category:"Menstruasi", statement:"Siklus menstruasi remaja bisa belum teratur pada beberapa tahun awal.", answer:"Fakta", explanation:"Pada masa awal menstruasi, siklus dapat bervariasi karena sistem hormonal masih beradaptasi.", takeaway:"Catat pola siklus dan konsultasikan bila perdarahan sangat berat, nyeri ekstrem, atau keluhan mengganggu aktivitas." },
  { id:"hygiene-1", category:"Kebersihan", statement:"Semakin banyak produk pewangi dipakai pada area genital, semakin sehat.", answer:"Mitos", explanation:"Produk berpewangi dapat memicu iritasi pada sebagian orang. Kebersihan lembut biasanya lebih aman daripada penggunaan produk berlebihan.", takeaway:"Gunakan cara membersihkan yang lembut dan hentikan produk yang menimbulkan iritasi." },
  { id:"hygiene-2", category:"Kebersihan", statement:"Mengganti pakaian dalam secara teratur membantu menjaga kebersihan area genital.", answer:"Fakta", explanation:"Pakaian yang bersih dan kering membantu kenyamanan dan mengurangi kelembapan berlebih.", takeaway:"Ganti pakaian dalam secara rutin terutama setelah banyak berkeringat atau basah." },
  { id:"pubertas-1", category:"Pubertas", statement:"Semua remaja mengalami pubertas pada usia yang sama.", answer:"Mitos", explanation:"Waktu mulai pubertas berbeda pada setiap orang dan dipengaruhi berbagai faktor biologis serta lingkungan.", takeaway:"Perbedaan waktu pubertas tidak otomatis berarti ada masalah kesehatan." },
  { id:"pubertas-2", category:"Pubertas", statement:"Perubahan suasana hati dapat terjadi selama pubertas.", answer:"Fakta", explanation:"Perubahan hormon, lingkungan, dan proses perkembangan dapat memengaruhi emosi selama masa pubertas.", takeaway:"Tidur cukup, dukungan sosial, dan komunikasi yang baik dapat membantu menghadapi perubahan emosi." },
  { id:"testis-1", category:"Reproduksi", statement:"Nyeri testis mendadak dan berat bisa ditunggu sampai besok untuk melihat apakah hilang sendiri.", answer:"Mitos", explanation:"Nyeri testis yang mendadak dan berat dapat menjadi kondisi yang membutuhkan penilaian medis segera.", takeaway:"Segera cari pertolongan medis bila nyeri testis muncul tiba-tiba, berat, atau disertai bengkak/mual." },
  { id:"ims-1", category:"Reproduksi", statement:"Seseorang selalu bisa tahu dari penampilan apakah orang lain memiliki IMS.", answer:"Mitos", explanation:"Banyak infeksi menular seksual dapat tidak menunjukkan gejala yang terlihat. Penampilan tidak dapat memastikan status infeksi.", takeaway:"Informasi yang benar dan pemeriksaan medis adalah dasar penilaian yang lebih dapat diandalkan." },
  { id:"ims-2", category:"Reproduksi", statement:"Edukasi yang benar dan pemeriksaan kesehatan dapat membantu pencegahan serta deteksi IMS.", answer:"Fakta", explanation:"Pengetahuan yang tepat, perilaku pencegahan, dan pemeriksaan bila diperlukan merupakan bagian penting kesehatan reproduksi.", takeaway:"Gunakan sumber kesehatan tepercaya dan tenaga kesehatan bila butuh penilaian individual." },
  { id:"anemia-1", category:"Menstruasi", statement:"Kelelahan berlebihan saat menstruasi tidak pernah berkaitan dengan anemia.", answer:"Mitos", explanation:"Perdarahan menstruasi yang banyak dapat berkontribusi pada kekurangan zat besi dan anemia pada sebagian orang.", takeaway:"Periksa bila mudah lelah, pucat, pusing, atau menstruasi sangat banyak/berkepanjangan." },
  { id:"lifestyle-1", category:"Gaya Hidup", statement:"Begadang terus-menerus tidak berpengaruh pada kesehatan karena masih muda.", answer:"Mitos", explanation:"Kurang tidur dapat memengaruhi konsentrasi, suasana hati, energi, dan kesehatan secara keseluruhan.", takeaway:"Usahakan rutinitas tidur yang konsisten dan cukup sesuai kebutuhan usia." },
  { id:"lifestyle-2", category:"Gaya Hidup", statement:"Aktivitas fisik teratur bermanfaat untuk kesehatan tubuh dan suasana hati.", answer:"Fakta", explanation:"Aktivitas fisik yang sesuai kemampuan dapat mendukung kesehatan fisik, tidur, dan kesejahteraan mental.", takeaway:"Pilih aktivitas yang aman dan realistis untuk dilakukan secara rutin." },
];

export const mythFactCategories = ["Semua", ...Array.from(new Set(mythFactItems.map(i => i.category)))];
